let players=[];
const capacity=15;
const teamSize=5;
let rules=[];
let transactions=[];
let teams=[[],[],[]], attendanceCount=0, myPresence=false;
function stars(n){return '★'.repeat(n)+'<span style="color:#ddd">★</span>'.repeat(5-n)}
function render(){
 const confirmed=attendanceCount, vacancies=Math.max(capacity-confirmed,0), percent=Math.min((confirmed/capacity)*100,100);
 document.querySelector('#confirmedCount').textContent=confirmed;document.querySelector('#capacityCount').textContent=capacity;document.querySelector('#confirmationProgress').style.width=percent+'%';document.querySelector('#availableSpots').textContent=`Clube do Diário · ${vacancies} ${vacancies===1?'vaga':'vagas'}`;document.querySelector('#drawConfirmedCount').textContent=confirmed;document.querySelector('#drawVacancyCount').textContent=`${vacancies} ${vacancies===1?'vaga restante':'vagas restantes'}`;
 const contribution=[...players].sort((a,b)=>(b.g+b.a)-(a.g+a.a));const assists=[...players].sort((a,b)=>b.a-a.a);const scorers=[...players].sort((a,b)=>b.g-a.g);
 document.querySelector('#leaderboard').innerHTML=players.length?contribution.slice(0,4).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.g} gols · ${p.a} assistências</small></div><div class="rank-score">${p.g+p.a}<small> PART.</small></div></div>`).join(''):'<p class="empty-state">Ainda não há estatísticas de jogadores.</p>';
 document.querySelector('#assistLeaderboard').innerHTML=players.length?assists.slice(0,4).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.pos} · ${p.g} gols</small></div><div class="rank-score">${p.a}<small> ASSIST.</small></div></div>`).join(''):'<p class="empty-state">Ainda não há assistências registradas.</p>';
 document.querySelector('#goalsLeaderboard').innerHTML=players.length?scorers.slice(0,5).map((p,i)=>`<div class="rank-row"><b class="rank-num">0${i+1}</b><span class="rank-face" style="background:${p.color}">${p.face}</span><div class="rank-name">${p.name}<small>${p.pos} · ${p.j} peladas</small></div><div class="rank-score">${p.g}<small> GOLS</small></div></div>`).join(''):'<p class="empty-state">Ainda não há gols registrados.</p>';
 document.querySelector('#playersList').innerHTML=players.length?players.map(p=>`<div class="player-row"><div class="player-info"><span class="tiny-face" style="background:${p.color}">${p.face}</span><div><b>${p.name}</b><small>${p.foot} · “${p.phrase}”</small></div></div><span data-label="Posição">${p.pos}</span><span class="stars" data-label="Estrelas">${stars(p.stars)}</span><b data-label="Gols">${p.g}</b><b data-label="Assistências">${p.a}</b><b data-label="Jogos">${p.j}</b><div class="player-actions admin-only"><button class="row-actions edit-goals" data-id="${p.id}" data-name="${p.name}" data-goals="${p.g}" aria-label="Editar gols de ${p.name}">⚽</button><button class="row-actions delete-player" data-id="${p.id}" aria-label="Excluir ${p.name}">×</button></div></div>`).join(''):'<p class="empty-state">Nenhum jogador cadastrado ainda.</p>';
 document.querySelector('#teamsGrid').innerHTML=teams.map((team,i)=>{let power=team.length?(team.reduce((a,p)=>a+p.stars,0)/team.length).toFixed(1):'—';let name=`TIME ${i+1}`;let slots=[...team,...Array(Math.max(teamSize-team.length,0)).fill(null)];return `<article class="team-card"><div class="team-card-header"><div><small>${name}</small><h2>${name}</h2></div><div class="team-power"><b>${power}</b><span>FORÇA MÉDIA</span></div></div><div class="squad">${slots.map(p=>p?`<div class="squad-row"><span class="player-face" style="background:${p.color}">${p.face}</span><div><b>${p.name}</b><small>${p.foot} · ${p.phrase}</small></div><span class="position">${p.pos.toUpperCase()}</span><span class="stars">${stars(p.stars)}</span></div>`:`<div class="squad-row vacancy"><span class="player-face">+</span><div><b>Vaga disponível</b><small>Aguardando confirmação</small></div><span class="position">—</span><span class="stars">—</span></div>`).join('')}</div></article>`}).join('');
 document.querySelector('#transactions').innerHTML=transactions.length?transactions.map(t=>`<div class="transaction ${t[3]?'out':''}"><div class="transaction-icon">${t[3]?'↗':'↙'}</div><div><b>${t[0]}</b><small>${t[1]}</small></div><strong>${t[2]}</strong><button class="row-actions admin-only delete-finance" data-id="${t[4]}">×</button></div>`).join(''):'<p class="empty-state">Nenhuma movimentação financeira registrada.</p>';
 document.querySelector('#rulesList').innerHTML=rules.map((r,i)=>`<article class="rule"><b class="rule-num">${String(i+1).padStart(2,'0')}</b><div><h3>${r.title}</h3><p>${r.content}</p></div><button class="row-actions admin-only delete-rule" data-id="${r.id}">×</button></article>`).join('');
}
function openModal(title,body){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=body;document.querySelector('#modal').classList.add('open')}
document.querySelectorAll('[data-page],[data-go]').forEach(b=>b.addEventListener('click',()=>{const page=b.dataset.page||b.dataset.go;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.querySelector('#'+page).classList.add('active-page');document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelector('#breadcrumb').textContent=b.textContent.trim().toUpperCase();document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}));
document.querySelector('#adminToggle').addEventListener('click',()=>{if(currentUser?.role==='admin'){document.body.classList.toggle('admin-mode');const yes=document.body.classList.contains('admin-mode');document.querySelector('#adminToggle').innerHTML=yes?'✓ Modo administrador ativo':'<span>⚙</span> Área do administrador';}else openAuth(true)});
document.querySelector('#menuButton').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.querySelector('#closeModal').addEventListener('click',()=>document.querySelector('#modal').classList.remove('open'));
document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});
document.querySelector('#addPlayer').addEventListener('click',()=>openModal('Cadastrar jogador',`<form class="form-grid" id="playerForm"><input id="playerName" placeholder="Nome do jogador" required><select id="playerPosition" required><option value="">Posição</option><option>Atacante</option><option>Meia</option><option>Zagueiro</option><option>Goleiro</option></select><select id="playerFoot" required><option value="">Perna boa</option><option>Destro</option><option>Canhoto</option><option>Ambidestro</option></select><select id="playerStars" required><option value="">Estrelas</option><option value="1">⭐</option><option value="2">⭐⭐</option><option value="3">⭐⭐⭐</option><option value="4">⭐⭐⭐⭐</option><option value="5">⭐⭐⭐⭐⭐</option></select><textarea id="playerPhrase" placeholder="Uma frase do cria..."></textarea><p class="form-error" id="playerError"></p><button class="primary-btn">Salvar jogador</button></form>`));
document.querySelector('#newTransaction').addEventListener('click',()=>openModal('Lançar movimentação',`<form class="form-grid" id="financeForm"><input id="financeDescription" placeholder="Descrição" required><input id="financeAmount" type="number" min="0.01" step="0.01" placeholder="Valor (R$)" required><select id="financeKind"><option value="income">Entrada</option><option value="expense">Saída</option></select><p class="form-error" id="financeError"></p><button class="primary-btn">Salvar lançamento</button></form>`));
document.querySelector('#addRule').addEventListener('click',()=>openModal('Criar regra',`<form class="form-grid" id="ruleForm"><input id="ruleTitle" placeholder="Título da regra" required><textarea id="ruleContent" placeholder="Descreva a regra..." required></textarea><p class="form-error" id="ruleError"></p><button class="primary-btn">Salvar regra</button></form>`));
document.addEventListener('click',e=>{const button=e.target.closest('.edit-goals');if(!button)return;openModal(`Gols de ${button.dataset.name}`,`<form class="form-grid" id="goalsForm" data-player-id="${button.dataset.id}"><label class="field-label" for="playerGoals">Quantidade de gols</label><input id="playerGoals" type="number" min="0" step="1" inputmode="numeric" value="${button.dataset.goals}" required><p class="form-error" id="goalsError"></p><button class="primary-btn">Salvar gols</button></form>`)});
document.querySelector('#reroll').addEventListener('click',()=>{teams.forEach(t=>t.sort(()=>Math.random()-.5));render()});
let currentUser=null, authMode='login', requestingAdmin=false;
const authModal=document.querySelector('#authModal'), authName=document.querySelector('#authName'), authPosition=document.querySelector('#authPosition'), authFoot=document.querySelector('#authFoot'), authPhrase=document.querySelector('#authPhrase'), authPassword=document.querySelector('#authPassword'), authError=document.querySelector('#authError');
function openAuth(admin=false){requestingAdmin=admin;authMode='login';authModal.classList.add('open');authModal.querySelector('.modal').classList.toggle('auth-admin',admin);document.querySelector('#authEyebrow').textContent=admin?'ÁREA RESTRITA':'BEM-VINDO À RESENHA';document.querySelector('#authTitle').textContent=admin?'Entrar como administrador':'Entrar';document.querySelector('#authCopy').textContent=admin?'Informe a senha de administrador para liberar o painel.':'Acesse sua conta para acompanhar a pelada.';authName.hidden=admin;authName.placeholder='Seu nome';authName.required=!admin;authPosition.hidden=true;authFoot.hidden=true;authPhrase.hidden=true;document.querySelector('#authSubmit').textContent='Entrar';authError.textContent='';authPassword.value='';}
function closeAuth(){authModal.classList.remove('open')}
function updateUser(user){currentUser=user;document.querySelector('#loginButton').textContent=user?`Olá, ${user.name.split(' ')[0]}`:'Entrar';document.querySelector('#userAvatar').textContent=user?user.name.slice(0,2).toUpperCase():'?';}
document.querySelector('#loginButton').addEventListener('click',()=>currentUser?fetch('/api/logout',{method:'POST'}).then(()=>{document.body.classList.remove('admin-mode');updateUser(null);loadAttendance()}):openAuth());
document.querySelector('#closeAuthModal').addEventListener('click',closeAuth);
authModal.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});
document.querySelectorAll('.auth-tab').forEach(button=>button.addEventListener('click',()=>{requestingAdmin=false;authMode=button.dataset.auth;document.querySelectorAll('.auth-tab').forEach(x=>x.classList.toggle('active',x===button));const signup=authMode==='signup';document.querySelector('#authTitle').textContent=signup?'Criar conta':'Entrar';document.querySelector('#authCopy').textContent=signup?'Crie sua conta e entre automaticamente na lista de jogadores.':'Acesse sua conta para acompanhar a pelada.';authName.hidden=false;authName.placeholder='Seu nome';authName.required=true;authPosition.hidden=!signup;authFoot.hidden=!signup;authPhrase.hidden=!signup;authPosition.required=signup;authFoot.required=signup;authPhrase.required=signup;document.querySelector('#authSubmit').textContent=signup?'Criar minha conta':'Entrar';authError.textContent=''}));
document.querySelector('#authForm').addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const payload=requestingAdmin?{admin:true,password:authPassword.value}:authMode==='signup'?{name:authName.value,password:authPassword.value,position:authPosition.value,foot:authFoot.value,phrase:authPhrase.value}:{name:authName.value,password:authPassword.value};const endpoint=authMode==='signup'&&!requestingAdmin?'/api/signup':'/api/login';const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){authError.textContent=data.error||'Não foi possível concluir a ação.';return}if(endpoint==='/api/signup'){authMode='login';document.querySelector('[data-auth="login"]').click();authError.style.color='#4c981c';authError.textContent='Conta criada e jogador adicionado. Agora entre com seus dados.';loadPlayers();return}updateUser(data.user);loadAttendance();closeAuth();if(data.user.role==='admin'){document.body.classList.add('admin-mode');document.querySelector('#adminToggle').innerHTML='✓ Modo administrador ativo'}});
fetch('/api/session').then(r=>r.json()).then(data=>{if(data.user)updateUser(data.user);loadAttendance()}).catch(()=>{});
async function loadFinance(){try{const response=await fetch('/api/finance');const data=await response.json();transactions=data.transactions.map(t=>[t.description,'Lançamento registrado',`${t.kind==='income'?'+':'−'} R$ ${Number(t.amount).toFixed(2).replace('.',',')}`,t.kind==='expense',t.id]);document.querySelector('#balanceValue').textContent=`R$ ${data.balance.toFixed(2).replace('.',',')}`;document.querySelector('#incomeValue').textContent=`R$ ${data.income.toFixed(2).replace('.',',')}`;document.querySelector('#expenseValue').textContent=`R$ ${data.expense.toFixed(2).replace('.',',')}`;document.querySelector('#homeBalance').textContent=`R$ ${data.balance.toFixed(2).replace('.',',')}`;render()}catch(e){}}
async function loadPlayers(){try{const data=await (await fetch('/api/players')).json();players=data.players.map(p=>({...p,pos:p.position,g:p.goals,a:p.assists,j:p.games,face:'⚽',color:'#dce5c3'}));render()}catch(e){}}
async function loadRules(){try{const data=await (await fetch('/api/rules')).json();rules=data.rules;render()}catch(e){}}
async function loadAttendance(){try{const data=await (await fetch('/api/attendance')).json();attendanceCount=data.confirmed;myPresence=data.mine;const button=document.querySelector('#presenceButton'),message=document.querySelector('#presenceMessage');if(!currentUser||currentUser.role!=='user'){button.textContent='Entrar para confirmar';message.textContent='Entre na sua conta para confirmar ou recusar sua presença.'}else if(myPresence){button.textContent='Cancelar confirmação';message.textContent='Sua presença está confirmada para a próxima pelada.'}else{button.textContent='Confirmar presença';message.textContent='Sua vaga ainda não está confirmada.'}render()}catch(e){}}
document.querySelector('#presenceButton').addEventListener('click',async()=>{if(!currentUser||currentUser.role!=='user'){openAuth();return}const response=await fetch('/api/attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:!myPresence})});if(response.ok)loadAttendance()});
document.addEventListener('submit',async e=>{if(!['financeForm','playerForm','ruleForm','goalsForm'].includes(e.target.id))return;e.preventDefault();let endpoint, payload, errorId, after;if(e.target.id==='financeForm'){endpoint='/api/finance';payload={description:document.querySelector('#financeDescription').value,amount:document.querySelector('#financeAmount').value,kind:document.querySelector('#financeKind').value};errorId='financeError';after=loadFinance}else if(e.target.id==='playerForm'){endpoint='/api/players';payload={name:document.querySelector('#playerName').value,position:document.querySelector('#playerPosition').value,foot:document.querySelector('#playerFoot').value,stars:document.querySelector('#playerStars').value,phrase:document.querySelector('#playerPhrase').value};errorId='playerError';after=loadPlayers}else if(e.target.id==='goalsForm'){endpoint=`/api/players/${e.target.dataset.playerId}/goals`;payload={goals:document.querySelector('#playerGoals').value};errorId='goalsError';after=loadPlayers}else{endpoint='/api/rules';payload={title:document.querySelector('#ruleTitle').value,content:document.querySelector('#ruleContent').value};errorId='ruleError';after=loadRules}const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){document.querySelector('#'+errorId).textContent=data.error;return}document.querySelector('#modal').classList.remove('open');after()});
document.addEventListener('click',async e=>{const button=e.target.closest('.delete-player,.delete-rule,.delete-finance');if(!button)return;const kind=button.classList.contains('delete-player')?'players':button.classList.contains('delete-rule')?'rules':'finance';if(!confirm('Excluir este item?'))return;const response=await fetch(`/api/${kind}/${button.dataset.id}`,{method:'DELETE'});if(!response.ok)return;if(kind==='players')loadPlayers();else if(kind==='rules')loadRules();else loadFinance()});
render();
loadFinance();
loadPlayers();
loadRules();
loadAttendance();
